### PR TITLE
Minor changes to menu list, and other text.

### PR DESCRIPTION
**Pull request by csgarza1984**
Changed menu list, cleaned up unneeded import statements, changed text in checkout  by author routine, added text when customer was successfully added or deleted.

### CODE REVIEW

**Review by MamtaGit-personal — APPROVED** [review]

**Review by MamtaGit-personal — APPROVED** [review]

**Comment by MamtaGit-personal** [comment]
Christine,

Thank you so much for all your work! We should freeze our code now.
Everything is working fine and nicely. We have put sufficient checks in
place to make sure our program doesn't crash.

So let's finish it. You may do a git push of your file with all the
snapshots with the latest changes that you have made, whenever you get a
chance tonight or tomorrow. I have accepted your changes in github.

Thanks,
Mamta

**Comment by csgarza1984** [comment]
Yay! We’re done! 😀
I’ll send the final screen shots later today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by csgarza1984** [comment]
Hi Mamta,

I added the Word docs with the screen shots to the git repository. One is for the code and one is for the running application. Let me know if you want it done differently or anything else.

Thanks for working on this project with me.

Chris

**Comment by MamtaGit-personal** [comment]
Christine,

Thank you so much! All the screenshots look great! We finished our project!
Yay!

You were an awesome team partner. It was a pleasure working with you!

Thanks,
Mamta

**Pull request merged**
